### ISSUE TITLE
ES_JAVA_OPTS in /etc/default/elasticsearch doesn't get used on systemd enabled systems.

### ISSUE THREAD

**Issue by aboe76** [saltstack-formulas/elasticsearch-formula#20]
more information:
https://www.elastic.co/guide/en/elasticsearch/reference/current/setting-system-settings.html#sysconfig
https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html

formula should be able to control /etc/elasticsearch/jvm.options.

**Comment by blbradley** [comment]
You are looking for [this] section of those docs. The `elasticsearch.conf` file is a systemd drop-in file that will override systemd directives in the service unit file shipped with the packages. You can use systemd `Environment` directives in the drop-in file to set your environment variables.

**Comment by blbradley** [comment]
It looks like `/etc/elasticsearch/jvm.options` could work on sysvinit or systemd. If that is true, that file will be fine to manage here.

**Comment by aboe76** [comment]
@blbradley I get it now, if no jvm.options file is in /etc/elasticsearch it will use the /etc/default/elasticsearch,

but the package will ship with an jvm.options file. so in order to work this file should be able to be manipulated.

**Comment by blbradley** [comment]
@aboe76 I think using `jvm.options` for all cases is less complex than than using `/etc/default/elasticsearch` or `/etc/sysconfig/elasticsearch`.

**Comment by aboe76** [comment]
@blbradley I think you are right, having only one place to set java options is beter,
and jvm.options file describes exactly what is does...

**Comment by blbradley** [comment]
Thank you! Send a PR if you like and I'll gladly review it.

**Comment by blbradley** [comment]
Closed by #28
