### ISSUE TITLE
JAVA_HOME managed by file.replace breaks idempotency

### ISSUE THREAD

**Issue by blbradley** [saltstack-formulas/elasticsearch-formula#27]
@cmclaughlin said in #26:

> file.replace was added to set JAVA_HOME in the sysconfig file, but that
results in the file changing every time the state is applied... and
then ElasticSearch restarts every time too.

**Comment by blbradley** [comment]
I think we need to find out if this is a bug in `file.replace` first.

**Comment by blbradley** [comment]
@cmclaughlin I would appreciate a bug report as detailed as SaltStack's main repo asks for.

**Comment by blbradley** [comment]
I found saltstack/salt#31127. Sounds similar. The regular expression I developed could be a bit off.

**Comment by blbradley** [comment]
I just checked for idempotency by running `bundle exec kitchen converge` twice. Second run had no changes.

So, I'll need more to reproduce. @cmclaughlin

**Comment by cmclaughlin** [comment]
@blbradley Sorry I didn't provide enough detail...

	----------
	          ID: /etc/sysconfig/elasticsearch
	    Function: file.managed
	      Result: True
	     Comment: File /etc/sysconfig/elasticsearch updated
	     Started: 20:33:13.938291
	    Duration: 15.857 ms
	     Changes:
	              ----------
	              diff:
	                  ---
	                  +++
	                  @@ -1,4 +1,3 @@
	                  -JAVA_HOME=/usr/bin/java
	                   ES_STARTUP_SLEEP_TIME=5
	                   MAX_OPEN_FILES=65536

	----------
	          ID: manage Elasticsearch JAVA_HOME in environment file
	    Function: file.replace
	        Name: /etc/sysconfig/elasticsearch
	      Result: True
	     Comment: Changes were made
	     Started: 20:33:13.954312
	    Duration: 2.051 ms
	     Changes:
	              ----------
	              diff:
	                  ---
	                  +++
	                  @@ -1,3 +1,4 @@
	                  +JAVA_HOME=/usr/bin/java
	                   ES_STARTUP_SLEEP_TIME=5
	                   MAX_OPEN_FILES=65536

	----------
	          ID: elasticsearch_service
	    Function: service.running
	        Name: elasticsearch
	      Result: True
	     Comment: Service restarted
	     Started: 20:33:13.985173
	    Duration: 10954.4 ms
	     Changes:
	              ----------
	              elasticsearch:
	                  True
	----------

/etc/sysconfig/elasticsearch is updated by both file.managed and file.replace and they sort of conflict with each other.

If you have elasticsearch:sysconfig defined in Pillar (which pillar.example does, btw), file.managed maintains the state of the file.  After that, file.replace updates the file to set JAVA_HOME.  

If you re-apply elasticsearch.sysconfig, file.managed will remove the JAVA_HOME entry and file.update will re-add it.... and the service is restarted every time.

**Comment by blbradley** [comment]
Thanks for the info! We need a better way to set the default `JAVA_HOME`.

**Comment by cmclaughlin** [comment]
Adding it to the `elasticsearch:sysconfig` Pillar seems good to me.  Any other ideas?

**Comment by cmclaughlin** [comment]
Oh, I guess you mean the formula should work with no Pillar data provided and JAVA_HOME should have a default value in that case.  I suppose we could do a check in the template file.  Something like this...?

	{%- if 'java_home' not in sysconfig.keys() %}
	JAVA_HOME=/usr/bin/java
	{% endif -%}
	{%- for key, value in sysconfig.iteritems() -%}
	{{ key }}={{ value }}
	{% endfor %}

**Comment by blbradley** [comment]
`{%- if 'java_home' not in sysconfig.keys() %}`

Brilliant! I like it.

**Comment by blbradley** [comment]
Thank you _SO_ much for taking more time to think about the solution.

**Comment by blbradley** [comment]
I'd recommend starting a new pull request and closing #26.

**Comment by cmclaughlin** [comment]
I re-used PR #26.  My laptop super slow running the tests, so I'm waiting to see if they pass on Travis.

**Comment by blbradley** [comment]
Closed by #27
