### ISSUE TITLE
elasticsearch.plugins state apparently missing

### ISSUE THREAD

**Issue by yoelcabo** [saltstack-formulas/elasticsearch-formula#4]
I cannot see any elasticsearch.plugins state. It is possible that you forgot to add the sls to dee6a41 ?

That is causing the state not to compile:
```
sudo salt server state.sls elasticsearch
server:
    Data failed to compile:
----------
    Specified SLS elasticsearch.plugins in saltenv base is not available on the salt master or through a configured fileserver
```

**Comment by simonclausen** [comment]
@martinhoefling, you wouldn't happen to have the plugins state laying around somewhere? :)

**Comment by martinhoefling** [comment]
Thanks @yoelcabo @simonclausen !
