### ISSUE TITLE
"Custom" configuration and validation of elasticsearch.yml settings

### ISSUE THREAD

**Issue by simonclausen** [saltstack-formulas/elasticsearch-formula#8]
This is related to #7 in the sense that I'm poking at some assumptions about how the formula should apply configuration and what it covers. I would like to open a discussion on these.

Right now the formula takes a number of directives for `elasticsearch.yml`, looks for these in the template and insets them into the rendered `elasticsearch.yml`.

Anything else (including `node.master` and `node.data`) are viewed as separate config, nested in `elasticsearch.config.custom_options`. These are passed along as is.

My question is if it makes sense to make this distinction - why not just pass along everything in `elasticsearch.config` directly to `elasticsearch.yml`?

**Comment by blbradley** [comment]
Hey! I'm trying to get this working in the formula. Please see #12. I need some discussion about backwards compatibility.

I did the work without looking at the issue first. You had a great idea!

**Comment by blbradley** [comment]
Closed by #12.

**Comment by blbradley** [comment]
Thanks for your suggestion!
